### ISSUE TITLE
Spawnfest TODO list 

### ISSUE THREAD

**Issue by elbow-jason** [spawnfest/graphql_smart_cell#2]
#  SPAWNFEST TODOS:

### Client 

We need a client to be able to:

+ [x] get client to make request to server - returning results of query or mutation

+ [x] fetch a schema
   + get introspection query to work
   + result should be json

+ [ ] ~subscriptions~
    + where
    + what
    + how

### Cells

Ideas for cells to work on:

+ [x] build client_cell - establish connection to a GraphQL server.
  + split the URI into fields on the form
  + might want to

+ [x] build query_cell - a cell for building graphql queries

  + [ ] use a schema to validate?

  + [x] simplest version is: present text field -> enter graphql query text -> press enter -> json

+ [ ] ~build json_table_reader_cell - turn json into Table.Reader protocol~
  + research Table.Reader protocol

+ [ ] build schema_viewing_cell

+ [ ] ~build force_directed_graph_cell~
  + Nodes and Edges?

**Comment by elbow-jason** [comment]
### Mike wants to see: 

- [ ] change query_cell: syntax sql -> graphql

- [ ] change query_cell: text field -> code-mirror

- [ ] 

- [ ] visualization for results

### Billy wants to see:

- [ ] all the above

- [ ] all the stuff requires a schema (so we should introspect the server? -Jason)
